name: Increment Build Version

on:
  push:

permissions:
  contents: write

jobs:
  increment-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Increment Build Number in README
        run: |
          if grep -q "^> Version: " README.md; then
            sed -E -i '/^> Version:/s/(.*[^0-9])([0-9]+)/echo "\1$((\2 + 1))"/e' README.md
            git add README.md
            git commit -m "Auto-increment build number"
            git push
          else
            echo "Version string not found, skipping update."
          fi
